### ISSUE TITLE
Add Activity model

### ISSUE THREAD

**Issue by bookis** [code-builders/calendar#11]
I breifly mentioned in #1 that a day should have any number of "Activities" (has_many) which should have:
- Start Time
- End Time
- Link
- Text

For each day there will be a sorted list of activities happening, like a daily schedule.

**Comment by bookis** [comment]
Here is a quick mockup of what those links will be on the site:

![daily-activiies](https://cloud.githubusercontent.com/assets/134635/9829467/99c420ba-58b9-11e5-8317-f647c04a6c56.png)

Does that make sense? Feel free to ping my if you need any clarification or want to talk through any of it.

**Comment by mistermayo** [comment]
Ah yes! Definitely makes sense. I thought it seemed too easy, must have
forgotten that activity bit! I'm glad to do another controller
